### ISSUE TITLE
About the pose information in CelebAMask-HQ

### ISSUE THREAD

**Issue by han265** [dunbar12138/pix2pix3D#37]
Hello, thanks for your excellent work and open-sourced code! The paper mentioned that there is pose information in the CeleAMask-HQ dataset. I wonder whether it's predicted by authors or not? And could you please give some suggestions on the pose prediction problem? Looking forward to your reply~

**Comment by dunbar12138** [comment]
We preprocess the dataset following https://github.com/NVlabs/eg3d?tab=readme-ov-file#preparing-datasets

**Comment by han265** [comment]
Thank you！
