### ISSUE TITLE
Which edge style is using?

### ISSUE THREAD

**Issue by MultiPath** [dunbar12138/pix2pix3D#4]
Thanks for sharing this amazing work.
Can I ask, in the edge-to-3D experiments, what style did you use with https://github.com/carolineec/informative-drawings
It has three styles in total: contour, anime, and opensketch.
Thanks

**Comment by dunbar12138** [comment]
Hi, thanks for your interest!

We used the contour style.

**Comment by MultiPath** [comment]
Thanks!
