### ISSUE TITLE
How to obtain the segmentation maps for cats?

### ISSUE THREAD

**Issue by MultiPath** [dunbar12138/pix2pix3D#8]
Hi, sorry for asking another question!
The paper says you used DINO features to cluster the cat face into segmentations.
Do you have the script for that?

**Comment by dunbar12138** [comment]
Hi, thanks for your interest!

We're using the script [here](https://github.com/ShirAmir/dino-vit-features/blob/main/part_cosegmentation.py) to get segmentation maps for cats.

**Comment by MultiPath** [comment]
Thank you very much!
